# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Movie.create(title: "Titanic", overview: "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic.", poster_url: "https://image.tmdb.org/t/p/original/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg", rating: 7.9)
Movie.create(title: "Only Lovers Left Alive", overview: "A depressed musician reunites with his lover. Though their romance, which has already endured several centuries, is disrupted by the arrival of her uncontrollable younger sister.", poster_url: "https://m.media-amazon.com/images/M/MV5BMTY0NTQ1NjA0OV5BMl5BanBnXkFtZTgwMDg5NjkzMTE@._V1_.jpg", rating: 7.2)
Movie.create(title: "Illusions Perdues", overview: "Story of the rise and the fall of a young man in Paris who dreamed to be a writer and became a journalist.", poster_url: "https://m.media-amazon.com/images/M/MV5BMGQ3NTdkZWMtNjFjNy00NDhkLThiYzQtZjY2Njk1YTczNTg0XkEyXkFqcGdeQXVyNDU0NjMyNTQ@._V1_FMjpg_UY720_.jpg", rating: 7.5)
Movie.create(title: "Belle de Jour", overview: "A frigid young housewife decides to spend her midweek afternoons as a prostitute.", poster_url: "https://m.media-amazon.com/images/M/MV5BZjNkNGJjYWEtM2IyNi00ZjM5LWFlYjYtYjQ4NTU5MGFlMTI2XkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_.jpg", rating: 7.7)
Movie.create(title: "Plein Soleil", overview: "Tom Ripley is a talented mimic, moocher, forger and all-around criminal improviser; but there's more to Tom Ripley than even he can guess.", poster_url: "https://m.media-amazon.com/images/M/MV5BOGZkMjQxM2YtMzEyMS00ZjQyLWE1NzAtZTUwMmQ5MDY5YzNjXkEyXkFqcGdeQXVyODQ0OTczOQ@@._V1_.jpg", rating: 7.7)
Movie.create(title: "A Bigger Splash", overview: "The vacation of a famous rock star and her boyfriend in Italy is disrupted by the unexpected visit of an old friend and his daughter.", poster_url: "https://m.media-amazon.com/images/M/MV5BMTkxNzk3NzMwN15BMl5BanBnXkFtZTgwODc3ODQ4NzE@._V1_FMjpg_UY720_.jpg", rating: 6.4)
Movie.create(title: "The Grand Budapest Hotel", overview: "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years under an exceptional concierge.", poster_url: "https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_FMjpg_UY720_.jpg", rating: 8.1)
Movie.create(title: "The Great Beauty", overview: "Jep Gambardella has seduced his way through the lavish nightlife of Rome for decades, but after his 65th birthday and a shock from the past, Jep looks past the nightclubs and parties to find a timeless landscape of absurd, exquisite beauty.", poster_url: "https://m.media-amazon.com/images/M/MV5BMWU5NmE2ZTUtYzhkMi00N2JmLWJhODgtM2NhNWU5ZWE5MTRlXkEyXkFqcGdeQXVyNDE5MTU2MDE@._V1_.jpg", rating: 7.7)
Movie.create(title: "The Dreamers", overview: "A young American studying in Paris in 1968 strikes up a friendship with a French brother and sister. Set against the background of the '68 Paris student riots.", poster_url: "https://m.media-amazon.com/images/M/MV5BN2JlNDM0YjQtNjg3NC00MWY0LTk0MmMtMTVkMmU0MDQ4MGMzXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg", rating: 7.2)
Movie.create(title: "Un été brûlant", overview: "The once-happy marriage between brooding painter Frederic and his movie-star wife Angele hits the rocks when another couple joins them on a Roman holiday.", poster_url: "https://m.media-amazon.com/images/M/MV5BZDExNWY1MTUtYmM4Ny00MmNjLTlkNTMtZjFlN2EwNmEyOGVkXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg", rating: 5.0)
